### ISSUE TITLE
Knative Hackethon

### ISSUE THREAD

**Issue by catvec** [knative-scout/meta#10]
Let's start planning this.

What do we need to figure out?

**Comment by catvec** [comment]
- Where?
  - Can remote people participate?
- When?
- Who?
- Prizes?
- Will we have a prompt or just "anything knative"?
- What learning resources do we need to create for people?
- How should be publicize so people actually come?
- Compute?
  - Should we give contestants a cluster? 
  - Namespace for each with resource quota?
- Food?

**Comment by janiejaffe** [comment]
- I would lean towards westford because space is less scarce and also we won't have to travel.
- Having one core event, but having remote submissions allowed would be best
- Beginning of August, gives us 2 weeks to put everything together
- I've heard a lot that people other than interns would be interested, so I think having it be broadly anyone at Red Hat who wants to show up and participate would be good. We could have participants have to sign up so we know how many people we'll have.
- prizes would be cool but I'm not sure how we'd get some
- We should have a broad and vague theme to give people something to jump off of, like a single word prompt. Just something fun to get people thinking, no serious limitations with it.
- In terms of learning resources we'd need first just a basic guide in terms of how to develop for knative. It could be useful to have hello-worlds pre set up for several different languages/frameworks on different repositories people could clone to get started quickly.
- Publicity seems fairly simple, we can post to different memo list as well as through all the intern channels. If we make a graphic we could probably get it put up on the screens. Also we can talk to people through slack, I'm sure the serverless team would be interested.
- Giving each participant a temp cluster seems like A Lot, but I don't know if there is an easier way? Can we do something with minikube?
- Food we should definitely have and is definitely the easiest part of planning this.

**Comment by VaishnaviHire** [comment]
Just to emphasize some of the above points -

- Event in Westford office and accepting remote submissons would be a good start.
- I think if we use minikube/ minishift, participants need to install knative, istio. Instead it would be great if we could give them access to knative installed cluster
- We can co-ordinate with intern program managers for publicity, food and prizes.

**Comment by janiejaffe** [comment]
What if we built preset openshift che setups so people wouldn't need to install a ton of stuff locally, would that be doable/helpful?

**Comment by catvec** [comment]
we are now tracking this in the Hackathon Proposal Google doc. See #kscout channel on slack.

If you would like to gain access to this document see the [requesting access docs.](https://github.com/kscout/site-reliability/blob/master/about/communication.md#requesting-access).
